"use strict";

global.grobal  = {a:'mooo'} // global variable!!!!!

var OldDeadunit = require('deadunit')
var Unit = require('../deadunitCore.node')
var Future = require('async-future')

var tests = require("./deadunitTests")

// these two are required for the 'sourcemap' test, but need to be here because the files can't be built into the bundle (or the sourcemap comment will eff things up)
require('./inlineSourceMapTest.umd')
require('./sourceMapTest.js') // generated by coffeescript
require('./generated/webpackTest.js.bundle.js')
require('./deadlinkSourcemapPath.umd.js')
require('./deadlinkSourceOriginal.umd.js')

var mainTest = OldDeadunit.test(tests.name, function(t) {






    //*
    this.test('node-specific tests', function() {
        this.count(1)
        this.timeout(30 * 1000)

        // when using fibers/futures, sometimes incorrect causes a future to never be resolved,
        // which causes the program to exit in what should be the middle of a continuation
        // this test is about making sure that you can at least see the results that were collected within that incomplete test
        this.test('fibers/futures - never-resolved future problem', function(t) {
            this.count(10)

            var Fiber = require('fibers')
            var FibersFuture = require('fibers/future')

            var f = new Future, f2 = new Future
            var ff = new FibersFuture

            var test = Unit.test(function() {
                this.count(2) // timeout
                this.timeout(100) // timeout faster

                setTimeout(function() {
                    Fiber(function() {
                        f.return()
                        this.test("Dead fiber after results", function() {
                            this.ok(true)
                            ff.wait()
                            this.ok(false) // not supposed to get here
                        })
                    }.bind(this)).run()
                }.bind(this),0)

                setTimeout(function() {
                    Fiber(function() {
                        f2.return()
                        this.test("Dead fiber before any results", function() { // this previously caused the duration to show up as NaN
                            ff.wait()
                            this.ok(false) // not supposed to get here
                        })
                    }.bind(this)).run()
                }.bind(this),0)
            }).events({end: function() {
                Future.all([f,f2]).then(function() {
                    var results = test.results()

                    t.ok(results.results.length === 3, results.results.length)

                    var subtest1 = results.results[1]
                    t.ok(subtest1.exceptions.length === 0, require('util').inspect(subtest1.exceptions))
                    t.ok(subtest1.results.length === 1, subtest1.results.length)
                    t.ok(subtest1.results[0].success === true)
                    t.ok(subtest1.duration !== undefined, subtest1.duration)
                    t.ok(subtest1.duration >= 0, results.results[0].duration)

                    subtest1 = results.results[2]
                    t.ok(subtest1.exceptions.length === 0, require('util').inspect(results.results[0].exceptions))
                    t.ok(subtest1.results.length === 0)
                    t.ok(subtest1.duration !== undefined, subtest1.duration)
                    t.ok(subtest1.duration >= 0, subtest1.duration)
                }).done()
            }})
        })



    })


    this.test('common tests', tests.getTests(Unit, 'node'))

    //*/


}).writeConsole(500)



// returns a function that calls a different function every time
// when it runs out of functions, it errors
function sequence() {
    var n = 0
    return function() {
        var fns = arguments
        n++
        if(n-1 >= fns.length) throw Error("Unexpected call "+n)
        fns[n-1]()

    }
}